---
version: '2'

services:

  redis:
    image: "redis:latest"
    ports:
        - "6379:6379"

  rediscommander:
      container_name: rediscommander
      hostname: rediscommander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
      - REDIS_HOSTS=local:redis:6379
      ports:
      - "8082:8081"
