module.exports = function (request) {
  const response = request.response

  this.trace = request.id
  this.errors = [{
    code: response.name.toLowerCase(),
    // Trim the message prefix generated by the error handler.
    message: response.message.replace(/^Uncaught error:\s*(.+)/, '$1')
  }]
}
